### ISSUE TITLE
Write Blog week-3

### ISSUE THREAD

**Issue by appuCoding** [shenzm/cs5610#1]
Write Blog Every week

**Comment by shenzm** [comment]
What content should I cover in the blog?

**Comment by appuCoding** [comment]
Check my blog page given below : 

http://net4.ccs.neu.edu/home/snehav27/blog/

**Comment by shenzm** [comment]
Blog post for the first 3 weeks is added, please check.

**Comment by shenzm** [comment]
Check v1.3 please
